### ISSUE TITLE
Why do you have both requirements.in and requirements.txt? 

### ISSUE THREAD

**Issue by stefsy** [SiliconValleyInsight/flask-api-template#3]

**Comment by benigeri** [comment]
Requirements.txt is for the package manager to know exactly which packages and versions to install (incl. all of their dependencies)

Requirements.in is a human readable list of the specific packages we are using in the app. For example, we put `Flask` in .in, but there ends up being 5-6 packages and specific versions in .txt. We don't *need* this, but it's nice to know what packages we actually user.
